- type: is-json
  value:
    required: ["greeting"]
    type: object
    properties:
      greeting:
        type: string
- type: llm-rubric
  provider: ollama:mistral:7b
  value: |
    The greeting should be:
    1. Warm and personalized - addressing the person by name
    2. Contextually appropriate to the time of day (morning, afternoon, evening, night)
    3. Professional and helpful
    Grade as PASS if it meets all three criteria, FAIL otherwise.